"""IO adapters for tetragrammatron projection surfaces."""

from .projective_time import TimeSignature, can_sync, xml_time_signature
from .p_adic_time import PAdicClock, can_sync_p_adic, signature_to_clock
from .xml_projection import companion_xml_block, projection_metadata, xml_to_world, world_to_xml
from .klein_blackboard import (
  KleinBlackboardError,
  KleinRelationalEngine,
  RelationalMachine,
  apply_relation,
  coxeter_mask_sequence,
  decode_configuration,
  encode_configuration,
  min_hamming_distance,
  validate_klein_incidence,
)
from .ast_spherepack import (
  AstSpherepackError,
  compress_ast,
  compress_input_payload,
  compress_javascript_sources,
  compress_python_sources,
  expand_bundle,
  validate_bundle,
  validate_input_payload,
)
from .agent_lifecycle import (
  AgentLifecycleError,
  build_agent_snapshot,
  canonical_source,
  compare_agent_snapshots,
  sid_from_source,
  validate_agent_snapshot,
)
from .reversible_time import (
  ReversibleTimeError,
  ReversibleTimeline,
  advance_point,
  pack_deltas,
  rewind_point,
  step_vector,
  unpack_deltas,
)
from .perles_identity import (
  PerlesIdentityError,
  control_code_cube_model,
  perles_coord_to_index,
  perles_index_to_coord,
  sid_to_perles_anchor,
  tension_signature,
)
from .light_garden_sphere import (
  LightGardenSphereError,
  compute_centroid,
  decode_frame,
  encode_frame,
  encode_sphere,
  validate_frame,
)
from .fano_scheduler import (
  FANO_LINES,
  FanoProcess,
  FanoScheduler,
  FanoSchedulerError,
  next_on_line,
)
from .control_superposition import (
  SCHEMA_V as CONTROL_SUPERPOSITION_SCHEMA_V,
  ControlSuperpositionError,
  canonical_control_superposition,
  validate_control_superposition,
)
from .living_xml import (
  LivingXmlError,
  advance_living_xml,
  circulation_role,
  circulation_trace,
  next_fano_tick,
  parse_living_xml,
)
from .agent_memory import (
  SCHEMA_V as AGENT_MEMORY_SCHEMA_V,
  AgentMemoryError,
  canonical_agent_memory_state,
  compute_sid,
  get_agent_frame,
  head_agent_sid,
  put_agent_frame,
  traverse_agent_memory,
  validate_agent_memory_state,
)
from .seed_algebra import (
  SCHEMA_V as SEED_ALGEBRA_SCHEMA_V,
  SeedAlgebraError,
  build_seed_entity,
  closure_fixpoint,
  compose_and,
  compose_xor,
  invariant_digest,
  phase,
  phase_from_header,
  popcount7,
  shared_phase,
  step_closure,
  validate_seed_entity,
)
from .seed_companion import (
  COMPANION_NS as SEED_COMPANION_NS,
  COMPANION_V as SEED_COMPANION_V,
  SeedCompanionError,
  build_companion,
  companion_from_xml,
  companion_reference,
  companion_to_xml,
  derive_seed_from_wave27h_report,
  to_projection_metadata,
  validate_companion,
  validate_companion_wave27h_continuity,
)
from .lane16 import (
  SCHEMA_V as LANE16_SCHEMA_V,
  ALLOWED_STATES as LANE16_ALLOWED_STATES,
  CHANNELS as LANE16_CHANNELS,
  Lane16Error,
  Lane16System,
  control_code,
  encode_lane_state,
  fano_pcg_check,
  lane_pair_digest,
  lane_phase,
  lane_sid,
  lane_step,
  system_sid,
  validate_lane_index,
  validate_lane_state,
  validate_lane_states,
)

__all__ = [
  "world_to_xml",
  "xml_to_world",
  "projection_metadata",
  "companion_xml_block",
  "TimeSignature",
  "xml_time_signature",
  "can_sync",
  "PAdicClock",
  "signature_to_clock",
  "can_sync_p_adic",
  "KleinBlackboardError",
  "RelationalMachine",
  "KleinRelationalEngine",
  "encode_configuration",
  "decode_configuration",
  "apply_relation",
  "coxeter_mask_sequence",
  "validate_klein_incidence",
  "min_hamming_distance",
  "AstSpherepackError",
  "compress_ast",
  "validate_input_payload",
  "compress_input_payload",
  "compress_python_sources",
  "compress_javascript_sources",
  "validate_bundle",
  "expand_bundle",
  "AgentLifecycleError",
  "canonical_source",
  "sid_from_source",
  "build_agent_snapshot",
  "validate_agent_snapshot",
  "compare_agent_snapshots",
  "ReversibleTimeError",
  "ReversibleTimeline",
  "step_vector",
  "advance_point",
  "rewind_point",
  "pack_deltas",
  "unpack_deltas",
  "PerlesIdentityError",
  "perles_index_to_coord",
  "perles_coord_to_index",
  "sid_to_perles_anchor",
  "tension_signature",
  "control_code_cube_model",
  "LightGardenSphereError",
  "compute_centroid",
  "encode_frame",
  "decode_frame",
  "validate_frame",
  "encode_sphere",
  "FANO_LINES",
  "FanoSchedulerError",
  "FanoProcess",
  "FanoScheduler",
  "next_on_line",
  "CONTROL_SUPERPOSITION_SCHEMA_V",
  "ControlSuperpositionError",
  "validate_control_superposition",
  "canonical_control_superposition",
  "LivingXmlError",
  "next_fano_tick",
  "circulation_role",
  "parse_living_xml",
  "advance_living_xml",
  "circulation_trace",
  "AGENT_MEMORY_SCHEMA_V",
  "AgentMemoryError",
  "compute_sid",
  "validate_agent_memory_state",
  "canonical_agent_memory_state",
  "put_agent_frame",
  "get_agent_frame",
  "head_agent_sid",
  "traverse_agent_memory",
  "SEED_ALGEBRA_SCHEMA_V",
  "SeedAlgebraError",
  "step_closure",
  "closure_fixpoint",
  "popcount7",
  "phase_from_header",
  "phase",
  "compose_xor",
  "compose_and",
  "shared_phase",
  "build_seed_entity",
  "validate_seed_entity",
  "invariant_digest",
  "SEED_COMPANION_V",
  "SEED_COMPANION_NS",
  "SeedCompanionError",
  "build_companion",
  "validate_companion",
  "validate_companion_wave27h_continuity",
  "derive_seed_from_wave27h_report",
  "companion_reference",
  "to_projection_metadata",
  "companion_to_xml",
  "companion_from_xml",
  "LANE16_SCHEMA_V",
  "LANE16_ALLOWED_STATES",
  "LANE16_CHANNELS",
  "Lane16Error",
  "Lane16System",
  "validate_lane_index",
  "validate_lane_state",
  "validate_lane_states",
  "lane_step",
  "lane_phase",
  "lane_sid",
  "system_sid",
  "control_code",
  "encode_lane_state",
  "fano_pcg_check",
  "lane_pair_digest",
]
